/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_stb_image_StbImage */

#ifndef _Included_generaloss_stb_image_StbImage
#define _Included_generaloss_stb_image_StbImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    failureReason
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_stb_image_StbImage_failureReason
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    info
 * Signature: (Ljava/lang/String;[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_info
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromFile
 * Signature: (J[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromFile
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromMemory
 * Signature: (Ljava/nio/ByteBuffer;I[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromMemory
  (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIoCallbacks;J[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromCallbacks
  (JNIEnv *, jclass, jobject, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setFlipVerticallyOnLoad
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setFlipVerticallyOnLoad
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setFlipVerticallyOnLoadThread
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setFlipVerticallyOnLoadThread
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setUnpremultiplyOnLoad
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setUnpremultiplyOnLoad
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setUnpremultiplyOnLoadThread
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setUnpremultiplyOnLoadThread
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load
 * Signature: (Ljava/lang/String;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromFile
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromFile
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromMemory
 * Signature: ([B[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIoCallbacks;J[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromCallbacks
  (JNIEnv *, jclass, jobject, jlong, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadfFromFile
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadfFromFile
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromFile16
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromFile16
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    imageFree
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_imageFree
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
