/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_stb_image_StbImage */

#ifndef _Included_generaloss_stb_image_StbImage
#define _Included_generaloss_stb_image_StbImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load
 * Signature: (Ljava/lang/String;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromMemory
 * Signature: ([B[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    imageFree
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_imageFree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    info
 * Signature: (Ljava/lang/String;[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_info
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setFlipVerticallyOnLoad
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setFlipVerticallyOnLoad
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
