/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_stb_image_StbImage */

#ifndef _Included_generaloss_stb_image_StbImage
#define _Included_generaloss_stb_image_StbImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    failureReason
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_stb_image_StbImage_failureReason
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    info
 * Signature: (Ljava/lang/String;[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_info
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromFile
 * Signature: (J[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromFile
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromMemory
 * Signature: ([B[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    infoFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;[I[I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_infoFromCallbacks
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setFlipVerticallyOnLoad
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setFlipVerticallyOnLoad
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setFlipVerticallyOnLoadThread
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setFlipVerticallyOnLoadThread
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setUnpremultiplyOnLoad
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setUnpremultiplyOnLoad
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    setUnpremultiplyOnLoadThread
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_setUnpremultiplyOnLoadThread
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load
 * Signature: (Ljava/lang/String;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromFile
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromFile
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromMemory
 * Signature: ([B[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromCallbacks
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadGifFromMemory
 * Signature: ([B[I[I[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadGifFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadf
 * Signature: (Ljava/lang/String;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadf
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadfFromFile
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadfFromFile
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadfFromMemory
 * Signature: ([B[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadfFromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadfFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadfFromCallbacks
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load16
 * Signature: (Ljava/lang/String;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load16
  (JNIEnv *, jclass, jstring, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    loadFromFile16
 * Signature: (Ljava/io/File;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_loadFromFile16
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load16FromMemory
 * Signature: ([B[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load16FromMemory
  (JNIEnv *, jclass, jbyteArray, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    load16FromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;[I[I[II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_stb_image_StbImage_load16FromCallbacks
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    imageFree
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_imageFree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    hdrToLdrGamma
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_hdrToLdrGamma
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    hdrToLdrScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_hdrToLdrScale
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    ldrToHdrGamma
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_ldrToHdrGamma
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    ldrToHdrScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_ldrToHdrScale
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    convertIphonePngToRgb
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_convertIphonePngToRgb
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    convertIphonePngToRgbThread
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_generaloss_stb_image_StbImage_convertIphonePngToRgbThread
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    is16Bit
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_is16Bit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    is16BitFromFile
 * Signature: (Ljava/io/File;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_is16BitFromFile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    is16BitFromMemory
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_is16BitFromMemory
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    is16BitFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_is16BitFromCallbacks
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    isHdr
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_isHdr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    isHdrFromFile
 * Signature: (Ljava/io/File;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_isHdrFromFile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    isHdrFromMemory
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_isHdrFromMemory
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    isHdrFromCallbacks
 * Signature: (Lgeneraloss/stb/image/StbImageIOCallbacks;)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_stb_image_StbImage_isHdrFromCallbacks
  (JNIEnv *, jclass, jobject);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeBuffer
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeBuffer
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeMalloc
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeMalloc
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeMallocGuesssize
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeMallocGuesssize
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeMallocGuesssizeHeaderflag
 * Signature: ([BIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeMallocGuesssizeHeaderflag
  (JNIEnv *, jclass, jbyteArray, jint, jboolean);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeNoheaderBuffer
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeNoheaderBuffer
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     generaloss_stb_image_StbImage
 * Method:    zlibDecodeNoheaderMalloc
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_generaloss_stb_image_StbImage_zlibDecodeNoheaderMalloc
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
